### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by thomasmcinnis** [nhurlock/clownshow.nvim#1]
Hey this looks great but haven't succeeded with it yet!

I get the error below after enabling JestWatch and saving the test file

```
Error executing Lua callback: ...re/nvim/lazy/clownshow.nvim/lua/clownshow/marks/init.lua:56: invalid key: inv
alidate
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...re/nvim/lazy/clownshow.nvim/lua/clownshow/marks/init.lua:56: in function '_from'
        ...re/nvim/lazy/clownshow.nvim/lua/clownshow/marks/init.lua:64: in function 'status'
        ...re/nvim/lazy/clownshow.nvim/lua/clownshow/state/init.lua:86: in function 'pre_process'
        ...al/share/nvim/lazy/clownshow.nvim/lua/clownshow/init.lua:44: in function 'attach_to_buffer'
        ...al/share/nvim/lazy/clownshow.nvim/lua/clownshow/init.lua:55: in function 'start'
        ...al/share/nvim/lazy/clownshow.nvim/lua/clownshow/init.lua:95: in function <...al/share/nvim/lazy/clo
wnshow.nvim/lua/clownshow/init.lua:95>
```

Additionally here is my lua file for the plugin in case I am setting up wrong

```
return {
    'nhurlock/clownshow.nvim',
    event = {
        'BufEnter *.test.[tj]s',
        'BufEnter *.spec.[tj]s',
    },
    config = function()
        require('clownshow').setup {}
    end,
}
```

**Comment by nhurlock** [comment]
@thomasmcinnis this is a 0.10+ option, I've version-gated it which should get rid of the error you're seeing

**Comment by thomasmcinnis** [comment]
Unfortunately still throwing the error after updating plugin to latest commit on nvim 0.9.5
Gating might not be working as anticipated

(No errors on 0.10, but unable to get working either - when JestWatch invoke only see a momentary flash of the inline "●" and then nothing)

**Comment by nhurlock** [comment]
> Unfortunately still throwing the error after updating plugin to latest commit on nvim 0.9.5 Gating might not be working as anticipated

ah, you're right, corrected!

> (No errors on 0.10, but unable to get working either - when JestWatch invoke only see a momentary flash of the inline "●" and then nothing)

the quick flash will mean that the Jest job is exiting immediately so this may mean you'll need to either adjust the `project_root` or `jest_command` options to have it run the test the way you're project is expecting them to be run

i've just pushed an adjustment that uses better default root and command logic which should work in more cases
if that's still causing it to immediately stop the job, for troubleshooting, from the same directory you open nvim, what happens when you run `npx jest /path/to/your/test/file`?

**Comment by thomasmcinnis** [comment]
That is working as expected now 👍
The issue when testing with the 0.10 build would have been because I wasn't opening nvim in the project directory.

Nice work on this plugin its super nice now it is working as expected!
